AWSTemplateFormatVersion: '2010-09-09'

Parameters: 
  Name: 
    Description: Name of the s3
    Type: String
    Default: test
Description: S3 Resources

Resources: 
  S3Bucket:
    Type: AWS::S3::Bucket
    Properties: 
      BucketName: !Ref Name
      BucketEncryption:
        ServerSideEncryptionConfiguration: 
          - ServerSideEncryptionByDefault: 
              SSEAlgorithm: 'AES256'
