AWSTemplateFormatVersion: '2010-09-09'

Description: Environment Resources

Parameters: 
  Name: 
    Description: Name of the VPC
    Type: String
    Default: 'test'
  Environment: 
    Description: Version
    Type: String
    AllowedValues: 
      - dev
      - stage
      - prod
    Default: 'dev'
  CIDR:
    Description: VPC CIDR
    Type: String
    Default: '10.1.0.0/16'

Mappings: 
  NameChoose: 
    test:
      dev: test-dev
      stage: test-stage
      prod: test-prod
      
Resources:
  VPCStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Name : !Ref Name
        Environment : !Ref Environment
        CIDR : !Ref CIDR
      Tags: 
        - Key: Name
          Value: !FindInMap
            - NameChoose
            - !Ref Name
            - !Ref Environment
      TemplateURL: 'https://xxxxxx.s3.us-east-2.amazonaws.com/xxxx/vpc.template'

  SubnetStack1:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Name : !Ref Name
        Environment : !Ref Environment
        CIDR : 10.1.0.0/24
        VPCID : !GetAtt VPCStack.Outputs.VPCId
      Tags: 
        - Key: Name
          Value: !FindInMap
            - NameChoose
            - !Ref Name
            - !Ref Environment
      TemplateURL: 'https://xxxxxx.s3.us-east-2.amazonaws.com/xxxx/subnet.template'

  SubnetStack2:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Name : !Ref Name
        Environment : !Ref Environment
        CIDR : 10.1.2.0/24
        VPCID : !GetAtt VPCStack.Outputs.VPCId
      Tags: 
        - Key: Name
          Value: !FindInMap
            - NameChoose
            - !Ref Name
            - !Ref Environment
      TemplateURL: 'https://xxxxxx.s3.us-east-2.amazonaws.com/xxxx/subnet.template'

  SGStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Name : !Ref Name
        Environment : !Ref Environment
        VPCID : !GetAtt VPCStack.Outputs.VPCId
      Tags: 
        - Key: Name
          Value: !FindInMap
            - NameChoose
            - !Ref Name
            - !Ref Environment
      TemplateURL: 'https://xxxxxx.s3.us-east-2.amazonaws.com/xxxx/security.template'

  InstanceStack:
    Type: AWS::CloudFormation::Stack
    Properties: 
      Parameters: 
        Name : !Ref Name
        Environment : !Ref Environment
        SubnetID : !GetAtt SubnetStack1.Outputs.SubnetId
        SGID : !GetAtt SGStack.Outputs.SGID
      Tags: 
        - Key: Name
          Value: !FindInMap
            - NameChoose
            - !Ref Name
            - !Ref Environment
      TemplateURL: 'https://xxxxxx.s3.us-east-2.amazonaws.com/xxxx/instance.template'
