# Import 模版与原本的模版相比 Import 模版多了要导入的 Resource. 本示例中要导入的Resource 是restoreTable

AWSTemplateFormatVersion: '2010-09-09'

Description: This template will import restore DynamoDB table. 

Parameters:
  SourceTableName:
    Type: String
  TargetTableName:
    Type: String


Resources:
  Table1:
    Type: 'AWS::DynamoDB::Table'
    Properties:
      TableName: !Sub '${SourceTableName}'
      BillingMode: 'PAY_PER_REQUEST'
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: True
      AttributeDefinitions:
        - AttributeName: 'AlbumTitle'
          AttributeType: 'S'
        - AttributeName: 'Artist'
          AttributeType: 'S'
        - AttributeName: 'SongTitle'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'AlbumTitle'
          KeyType: 'HASH'
        - AttributeName: 'Artist'
          KeyType: 'RANGE'
      LocalSecondaryIndexes:
        - IndexName: 'AlbumTitleSongTitle'
          KeySchema:
            - AttributeName: 'AlbumTitle'
              KeyType: 'HASH'
            - AttributeName: 'SongTitle'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL
  restoreTable:
    Type: 'AWS::DynamoDB::Table'
    DeletionPolicy: "Retain"
    Properties:
      TableName: !Sub '${TargetTableName}'
      BillingMode: 'PAY_PER_REQUEST'
      PointInTimeRecoverySpecification:
        PointInTimeRecoveryEnabled: True
      AttributeDefinitions:
        - AttributeName: 'AlbumTitle'
          AttributeType: 'S'
        - AttributeName: 'Artist'
          AttributeType: 'S'
        - AttributeName: 'SongTitle'
          AttributeType: 'S'
      KeySchema:
        - AttributeName: 'AlbumTitle'
          KeyType: 'HASH'
        - AttributeName: 'Artist'
          KeyType: 'RANGE'
      LocalSecondaryIndexes:
        - IndexName: 'AlbumTitleSongTitle'
          KeySchema:
            - AttributeName: 'AlbumTitle'
              KeyType: 'HASH'
            - AttributeName: 'SongTitle'
              KeyType: 'RANGE'
          Projection:
            ProjectionType: ALL



